# Generated by Django 5.1.2 on 2024-10-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_rename_name_savedplace_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedplace',
            old_name='labels',
            new_name='label',
        ),
    ]
